---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cXdlcnR5MTM=

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  WORDPRESS_DB_USER: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: cXdlcnR5MTM=
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_TABLE_PREFIX: d3Bz